---
version: '3.0'
services:
  db:
    image: novucs/derby:10.14.2.0-jdk11-slim
    ports:
      - 1527:1527
    volumes:
      - db-data:/dbs

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
      - "4848:4848"
      - "9090:9090"
    volumes:
      - ./build/app.war:/app/glassfish/domains/domain1/autodeploy/app.war

volumes:
  db-data:
