---
version: '3.0'
services:
  db:
    image: novucs/derby:10.14.2.0-jdk11-slim
    ports:
      - 1527:1527
    volumes:
      - db-data:/dbs

  app:
    build: .
    command: ./glassfish/bin/asadmin start-domain --verbose --debug
    depends_on:
      - db
    environment:
      DB_URL: jdbc:derby://db:1527/esd;create=true
      DEVELOPMENT_MODE: 1
    ports:
      - "8080:8080"
      - "4848:4848"
      - "9009:9009"
    volumes:
      - ./build/app.war:/app/glassfish/domains/domain1/autodeploy/app.war

volumes:
  db-data:
